version: "3.8"

x-common-service: &common-service
  build:
    context: .
  env_file:
    - .env
  depends_on:
    - postgresql
  links:
    - postgresql
  restart: always
  volumes:
    - .:/app/src

services:
  devserver:
    <<: *common-service
    command: api
    environment:
      API_HOST: "0.0.0.0"
      API_POST: 8000
      API_RELOAD: "true"
    ports:
      - "8000:8000"

  scheduler:
    <<: *common-service
    command: scheduler

  worker:
    <<: *common-service
    command: worker

  postgresql:
    command: >
      postgres
        -c log_statement=none
        -c log_lock_waits=true
        -c log_min_duration_statement=-1
        -c log_min_error_statement=panic
    environment:
      - POSTGRES_INITDB_ARGS=--nosync
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=awesome-rss-reader
      - POSTGRES_DB=awesome-rss-reader
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    image: postgres:15.2
    ports:
      - "5432:5432"
    tmpfs:
      - /run
      - /var/run
      - /tmp
      - /var/lib/postgresql/data
    logging:
      driver: none
