apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "awesome-rss-reader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.uvicorn.port }}
      targetPort: {{ .Values.uvicorn.targetPort }}
      protocol: TCP
      name: uvicorn
  selector:
    {{- include "awesome-rss-reader.selectorLabels" . | nindent 4 }}
