name: Set up poetry environment
description: Set up poetry environment
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: .python-version
        cache: poetry

    - name: Install dependencies
      run: poetry install
      shell: bash
