name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: awesome-rss-reader
          POSTGRES_PASSWORD: awesome-rss-reader
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up poetry venv
        uses: ./.github/actions/setup-poetry-env

      - name: Run tests
        run: poetry run pytest --assert=plain --cov=awesome_rss_reader/ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up poetry venv
        uses: ./.github/actions/setup-poetry-env

      - name: Run mypy
        run: poetry run mypy awesome_rss_reader/
